spring.application.name=store-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeebeansdb
spring.datasource.username=postgres
spring.datasource.password=12345a
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SQL init — disabled since DB is already initialized
spring.sql.init.mode=never

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# JWT
app.jwt.secret=6A586E3272357538782F413F4428472B4B6250655368566D597133743677397A
app.jwt.expiration-ms=86400000

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Static resources (for uploaded images)
app.upload.dir=uploads

# App config
app.currency=ARS
app.low-stock-threshold=5

server.port=8080

logging.level.org.springframework.security=DEBUG

# Mercado Pago
app.mercadopago.access-token=APP_USR-5408981161601501-102622-b41a6988cbf7ae2bb8656abfc13711c2-2948292754
app.mercadopago.test-buyer-email=test_user_1261207542929735968@testuser.com
app.mercadopago.public-base-url=https://unpausing-dell-reversely.ngrok-free.dev

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.report.email.to=admin@coffeebeans.com
